name: Model Retraining on Push to Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%y%m%d%H%M%S')
        echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV
        echo "$timestamp" > timestamp.txt
      id: timestamp 

    - name: Check File Permissions
      run: |
        ls -l ./src/train_model.py

    - name: Set File Permissions
      run: |
        chmod +x ./src/train_model.py #making it executable

    - name: Retrain Model
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt)
        python ./src/eval.py --timestamp "$timestamp"
        metrics_filename="${timestamp}_metrics.json"
        echo "METRICS_FILENAME=$metrics_filename" >> $GITHUB_ENV
      continue-on-error: false

    - name: Store and Version the New Model
      run: |
        timestamp=$(cat timestamp.txt)
        echo "MODEL_FILENAME=model_${timestamp}_model.joblib" >> $GITHUB_ENV

    - name: Commit and Push Changes
      run: |
        git config --global user.email "karthiks233@gmail.com"
        git config --global user.name "karthiks233"
        git add metrics/ models/
        timestamp=$(cat timestamp.txt)
        git commit -m "Add metrics and updated model for timestamp $timestamp" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}